import telepot
import time
import urllib3

from telepot.loop import MessageLoop
from telepot.namedtuple import ReplyKeyboardMarkup, KeyboardButton, ReplyKeyboardRemove, ForceReply
from telepot.namedtuple import InlineKeyboardMarkup, InlineKeyboardButton
from telepot.namedtuple import InlineQueryResultArticle, InlineQueryResultPhoto, InputTextMessageContent

bot = telepot.Bot('rahasia')

radar = '/root/data/sepuluh/current/citra_radar.png'

call_data = {
  "WRF Rain 6": "/root/data/harian/wrf/6.png",
  "WRF Rain 12": "/root/data/harian/wrf/12.png",
  "WRF Rain 18": "/root/data/harian/wrf/18.png",
  "WRF Rain 24": "/root/data/harian/wrf/24.png",
  "WRF Rain 30": "/root/data/harian/wrf/30.png",
  "WRF Rain 36": "/root/data/harian/wrf/36.png",
  "WRF Rain 42": "/root/data/harian/wrf/42.png",
  "WRF Rain 48": "/root/data/harian/wrf/48.png",
  "WRF Rain 54": "/root/data/harian/wrf/54.png",
  "WRF Rain 60": "/root/data/harian/wrf/60.png",
  "WRF Rain 66": "/root/data/harian/wrf/66.png",
  "WRF Rain 72": "/root/data/harian/wrf/72.png",
  "WRF Rain 78": "/root/data/harian/wrf/78.png",
  "WRF Rain 84": "/root/data/harian/wrf/84.png",
  "WRF Rain 90": "/root/data/harian/wrf/90.png",
  "WRF Rain 96": "/root/data/harian/wrf/96.png",
  "WRF Rain 102": "/root/data/harian/wrf/102.png",
  "WRF Rain 108": "/root/data/harian/wrf/108.png",
  "WRF Rain 114": "/root/data/harian/wrf/114.png",
  "WRF Rain 120": "/root/data/harian/wrf/120.png",
  "BoM RAIN 6": "/root/data/harian/bom/6.png",
  "BoM RAIN 12": "/root/data/harian/bom/12.png",
  "BoM RAIN 18": "/root/data/harian/bom/18.png",
  "BoM RAIN 24": "/root/data/harian/bom/24.png",
  "BoM RAIN 30": "/root/data/harian/bom/30.png",
  "BoM RAIN 36": "/root/data/harian/bom/36.png",
  "BoM RAIN 42": "/root/data/harian/bom/42.png",
  "BoM RAIN 48": "/root/data/harian/bom/48.png",
  "BoM RAIN 54": "/root/data/harian/bom/54.png",
  "BoM RAIN 60": "/root/data/harian/bom/60.png",
  "BoM RAIN 66": "/root/data/harian/bom/66.png",
  "BoM RAIN 72": "/root/data/harian/bom/72.png",
  "BoM RAIN 78": "/root/data/harian/bom/78.png",
  "BoM RAIN 84": "/root/data/harian/bom/84.png",
  "BoM RAIN 90": "/root/data/harian/bom/90.png",
  "BoM RAIN 96": "/root/data/harian/bom/96.png",
  "BoM RAIN 102": "/root/data/harian/bom/102.png",
  "BoM RAIN 108": "/root/data/harian/bom/108.png",
  "BoM RAIN 114": "/root/data/harian/bom/114.png",
  "BoM RAIN 120": "/root/data/harian/bom/120.png",
  "BoM RAIN 126": "/root/data/harian/bom/126.png",
  "BoM RAIN 132": "/root/data/harian/bom/132.png",
  "BoM RAIN 138": "/root/data/harian/bom/138.png",
  "BoM RAIN 144": "/root/data/harian/bom/144.png",
  "BoM RAIN 150": "/root/data/harian/bom/150.png",
  "BoM RAIN 156": "/root/data/harian/bom/156.png",
  "BoM RAIN 162": "/root/data/harian/bom/162.png",
  "IFS RAIN 6": "/root/data/harian/ifs/rain/6.png",
  "IFS RAIN 12": "/root/data/harian/ifs/rain/12.png",
  "IFS RAIN 18": "/root/data/harian/ifs/rain/18.png",
  "IFS RAIN 24": "/root/data/harian/ifs/rain/24.png",
  "IFS RAIN 30": "/root/data/harian/ifs/rain/30.png",
  "IFS RAIN 36": "/root/data/harian/ifs/rain/36.png",
  "IFS RAIN 42": "/root/data/harian/ifs/rain/42.png",
  "IFS RAIN 48": "/root/data/harian/ifs/rain/48.png",
  "IFS RAIN 54": "/root/data/harian/ifs/rain/54.png",
  "IFS RAIN 60": "/root/data/harian/ifs/rain/60.png",
  "IFS RAIN 66": "/root/data/harian/ifs/rain/66.png",
  "IFS RAIN 72": "/root/data/harian/ifs/rain/72.png",
  "IFS RAIN 78": "/root/data/harian/ifs/rain/78.png",
  "IFS RAIN 84": "/root/data/harian/ifs/rain/84.png",
  "IFS RAIN 90": "/root/data/harian/ifs/rain/90.png",
  "IFS RAIN 96": "/root/data/harian/ifs/rain/96.png",
  "IFS RAIN 102": "/root/data/harian/ifs/rain/102.png",
  "IFS RAIN 108": "/root/data/harian/ifs/rain/108.png",
  "IFS RAIN 114": "/root/data/harian/ifs/rain/114.png",
  "IFS RAIN 120": "/root/data/harian/ifs/rain/120.png",
  "IFS RAIN 126": "/root/data/harian/ifs/rain/126.png",
  "IFS RAIN 132": "/root/data/harian/ifs/rain/132.png",
  "IFS RAIN 138": "/root/data/harian/ifs/rain/138.png",
  "IFS RAIN 144": "/root/data/harian/ifs/rain/144.png",
  "IFS RAIN 150": "/root/data/harian/ifs/rain/150.png",
  "IFS RAIN 156": "/root/data/harian/ifs/rain/156.png",
  "IFS RAIN 162": "/root/data/harian/ifs/rain/162.png",
  "IFS RAIN 168": "/root/data/harian/ifs/rain/168.png",
  "IFS RAIN 174": "/root/data/harian/ifs/rain/174.png",
  "IFS RAIN 180": "/root/data/harian/ifs/rain/180.png",
  "IFS KI 3": "/root/data/harian/ifs/KI/3.png",
  "IFS KI 6": "/root/data/harian/ifs/KI/6.png",
  "IFS KI 9": "/root/data/harian/ifs/KI/9.png",
  "IFS KI 12": "/root/data/harian/ifs/KI/12.png",
  "IFS KI 15": "/root/data/harian/ifs/KI/15.png",
  "IFS KI 18": "/root/data/harian/ifs/KI/18.png",
  "IFS KI 21": "/root/data/harian/ifs/KI/21.png",
  "IFS KI 24": "/root/data/harian/ifs/KI/24.png",
  "IFS KI 27": "/root/data/harian/ifs/KI/27.png",
  "IFS KI 30": "/root/data/harian/ifs/KI/30.png",
  "IFS KI 33": "/root/data/harian/ifs/KI/33.png",
  "IFS KI 36": "/root/data/harian/ifs/KI/36.png",
  "IFS KI 39": "/root/data/harian/ifs/KI/39.png",
  "IFS KI 42": "/root/data/harian/ifs/KI/42.png",
  "IFS KI 45": "/root/data/harian/ifs/KI/45.png",
  "IFS KI 48": "/root/data/harian/ifs/KI/48.png",
  "IFS KI 51": "/root/data/harian/ifs/KI/51.png",
  "IFS KI 54": "/root/data/harian/ifs/KI/54.png",
  "IFS KI 57": "/root/data/harian/ifs/KI/57.png",
  "IFS KI 60": "/root/data/harian/ifs/KI/60.png",
  "IFS KI 63": "/root/data/harian/ifs/KI/63.png",
  "IFS KI 66": "/root/data/harian/ifs/KI/66.png",
  "IFS KI 69": "/root/data/harian/ifs/KI/69.png",
  "IFS KI 72": "/root/data/harian/ifs/KI/72.png",
  "IFS KI 75": "/root/data/harian/ifs/KI/75.png",
  "IFS KI 78": "/root/data/harian/ifs/KI/78.png",
  "IFS KI 81": "/root/data/harian/ifs/KI/81.png",
  "IFS KI 84": "/root/data/harian/ifs/KI/84.png",
  "IFS KI 87": "/root/data/harian/ifs/KI/87.png",
  "IFS KI 90": "/root/data/harian/ifs/KI/90.png",
  "IFS KI 93": "/root/data/harian/ifs/KI/93.png",
  "IFS KI 96": "/root/data/harian/ifs/KI/96.png",
  "IFS KI 99": "/root/data/harian/ifs/KI/99.png",
  "IFS KI 102": "/root/data/harian/ifs/KI/102.png",
  "IFS KI 105": "/root/data/harian/ifs/KI/105.png",
  "IFS KI 108": "/root/data/harian/ifs/KI/108.png",
  "IFS KI 111": "/root/data/harian/ifs/KI/111.png",
  "IFS KI 114": "/root/data/harian/ifs/KI/114.png",
  "IFS KI 117": "/root/data/harian/ifs/KI/117.png",
  "IFS KI 120": "/root/data/harian/ifs/KI/120.png",
  "IFS KI 123": "/root/data/harian/ifs/KI/123.png",
  "IFS KI 126": "/root/data/harian/ifs/KI/126.png",
  "IFS KI 129": "/root/data/harian/ifs/KI/129.png",
  "IFS KI 132": "/root/data/harian/ifs/KI/132.png",
  "IFS KI 135": "/root/data/harian/ifs/KI/135.png",
  "IFS KI 138": "/root/data/harian/ifs/KI/138.png",
  "IFS KI 141": "/root/data/harian/ifs/KI/141.png",
  "IFS KI 144": "/root/data/harian/ifs/KI/144.png",
  "IFS KI 147": "/root/data/harian/ifs/KI/147.png",
  "IFS KI 150": "/root/data/harian/ifs/KI/150.png",
  "IFS KI 153": "/root/data/harian/ifs/KI/153.png",
  "IFS KI 156": "/root/data/harian/ifs/KI/156.png",
  "IFS KI 159": "/root/data/harian/ifs/KI/159.png",
  "IFS KI 162": "/root/data/harian/ifs/KI/162.png",
  "IFS KI 165": "/root/data/harian/ifs/KI/165.png",
  "IFS KI 168": "/root/data/harian/ifs/KI/168.png",
  "IFS KI 171": "/root/data/harian/ifs/KI/171.png",
  "IFS KI 174": "/root/data/harian/ifs/KI/174.png",
  "IFS KI 177": "/root/data/harian/ifs/KI/177.png",
  "IFS KI 180": "/root/data/harian/ifs/KI/180.png",
  "IFS KI 183": "/root/data/harian/ifs/KI/183.png",
  "IFS KI 186": "/root/data/harian/ifs/KI/186.png",
  "IFS KI 189": "/root/data/harian/ifs/KI/189.png",
  "IFS KI 192": "/root/data/harian/ifs/KI/192.png",
  "IFS KI 195": "/root/data/harian/ifs/KI/195.png",
  "IFS KI 198": "/root/data/harian/ifs/KI/198.png",
  "IFS SI 3": "/root/data/harian/ifs/SI/3.png",
  "IFS SI 6": "/root/data/harian/ifs/SI/6.png",
  "IFS SI 9": "/root/data/harian/ifs/SI/9.png",
  "IFS SI 12": "/root/data/harian/ifs/SI/12.png",
  "IFS SI 15": "/root/data/harian/ifs/SI/15.png",
  "IFS SI 18": "/root/data/harian/ifs/SI/18.png",
  "IFS SI 21": "/root/data/harian/ifs/SI/21.png",
  "IFS SI 24": "/root/data/harian/ifs/SI/24.png",
  "IFS SI 27": "/root/data/harian/ifs/SI/27.png",
  "IFS SI 30": "/root/data/harian/ifs/SI/30.png",
  "IFS SI 33": "/root/data/harian/ifs/SI/33.png",
  "IFS SI 36": "/root/data/harian/ifs/SI/36.png",
  "IFS SI 39": "/root/data/harian/ifs/SI/39.png",
  "IFS SI 42": "/root/data/harian/ifs/SI/42.png",
  "IFS SI 45": "/root/data/harian/ifs/SI/45.png",
  "IFS SI 48": "/root/data/harian/ifs/SI/48.png",
  "IFS SI 51": "/root/data/harian/ifs/SI/51.png",
  "IFS SI 54": "/root/data/harian/ifs/SI/54.png",
  "IFS SI 57": "/root/data/harian/ifs/SI/57.png",
  "IFS SI 60": "/root/data/harian/ifs/SI/60.png",
  "IFS SI 63": "/root/data/harian/ifs/SI/63.png",
  "IFS SI 66": "/root/data/harian/ifs/SI/66.png",
  "IFS SI 69": "/root/data/harian/ifs/SI/69.png",
  "IFS SI 72": "/root/data/harian/ifs/SI/72.png",
  "IFS SI 75": "/root/data/harian/ifs/SI/75.png",
  "IFS SI 78": "/root/data/harian/ifs/SI/78.png",
  "IFS SI 81": "/root/data/harian/ifs/SI/81.png",
  "IFS SI 84": "/root/data/harian/ifs/SI/84.png",
  "IFS SI 87": "/root/data/harian/ifs/SI/87.png",
  "IFS SI 90": "/root/data/harian/ifs/SI/90.png",
  "IFS SI 93": "/root/data/harian/ifs/SI/93.png",
  "IFS SI 96": "/root/data/harian/ifs/SI/96.png",
  "IFS SI 99": "/root/data/harian/ifs/SI/99.png",
  "IFS SI 102": "/root/data/harian/ifs/SI/102.png",
  "IFS SI 105": "/root/data/harian/ifs/SI/105.png",
  "IFS SI 108": "/root/data/harian/ifs/SI/108.png",
  "IFS SI 111": "/root/data/harian/ifs/SI/111.png",
  "IFS SI 114": "/root/data/harian/ifs/SI/114.png",
  "IFS SI 117": "/root/data/harian/ifs/SI/117.png",
  "IFS SI 120": "/root/data/harian/ifs/SI/120.png",
  "IFS SI 123": "/root/data/harian/ifs/SI/123.png",
  "IFS SI 126": "/root/data/harian/ifs/SI/126.png",
  "IFS SI 129": "/root/data/harian/ifs/SI/129.png",
  "IFS SI 132": "/root/data/harian/ifs/SI/132.png",
  "IFS SI 135": "/root/data/harian/ifs/SI/135.png",
  "IFS SI 138": "/root/data/harian/ifs/SI/138.png",
  "IFS SI 141": "/root/data/harian/ifs/SI/141.png",
  "IFS SI 144": "/root/data/harian/ifs/SI/144.png",
  "IFS SI 147": "/root/data/harian/ifs/SI/147.png",
  "IFS SI 150": "/root/data/harian/ifs/SI/150.png",
  "IFS SI 153": "/root/data/harian/ifs/SI/153.png",
  "IFS SI 156": "/root/data/harian/ifs/SI/156.png",
  "IFS SI 159": "/root/data/harian/ifs/SI/159.png",
  "IFS SI 162": "/root/data/harian/ifs/SI/162.png",
  "IFS SI 165": "/root/data/harian/ifs/SI/165.png",
  "IFS SI 168": "/root/data/harian/ifs/SI/168.png",
  "IFS SI 171": "/root/data/harian/ifs/SI/171.png",
  "IFS SI 174": "/root/data/harian/ifs/SI/174.png",
  "IFS SI 177": "/root/data/harian/ifs/SI/177.png",
  "IFS SI 180": "/root/data/harian/ifs/SI/180.png",
  "IFS SI 183": "/root/data/harian/ifs/SI/183.png",
  "IFS SI 186": "/root/data/harian/ifs/SI/186.png",
  "IFS SI 189": "/root/data/harian/ifs/SI/189.png",
  "IFS SI 192": "/root/data/harian/ifs/SI/192.png",
  "IFS SI 195": "/root/data/harian/ifs/SI/195.png",
  "IFS SI 198": "/root/data/harian/ifs/SI/198.png",
  "IFS LI 3": "/root/data/harian/ifs/LI/3.png",
  "IFS LI 6": "/root/data/harian/ifs/LI/6.png",
  "IFS LI 9": "/root/data/harian/ifs/LI/9.png",
  "IFS LI 12": "/root/data/harian/ifs/LI/12.png",
  "IFS LI 15": "/root/data/harian/ifs/LI/15.png",
  "IFS LI 18": "/root/data/harian/ifs/LI/18.png",
  "IFS LI 21": "/root/data/harian/ifs/LI/21.png",
  "IFS LI 24": "/root/data/harian/ifs/LI/24.png",
  "IFS LI 27": "/root/data/harian/ifs/LI/27.png",
  "IFS LI 30": "/root/data/harian/ifs/LI/30.png",
  "IFS LI 33": "/root/data/harian/ifs/LI/33.png",
  "IFS LI 36": "/root/data/harian/ifs/LI/36.png",
  "IFS LI 39": "/root/data/harian/ifs/LI/39.png",
  "IFS LI 42": "/root/data/harian/ifs/LI/42.png",
  "IFS LI 45": "/root/data/harian/ifs/LI/45.png",
  "IFS LI 48": "/root/data/harian/ifs/LI/48.png",
  "IFS LI 51": "/root/data/harian/ifs/LI/51.png",
  "IFS LI 54": "/root/data/harian/ifs/LI/54.png",
  "IFS LI 57": "/root/data/harian/ifs/LI/57.png",
  "IFS LI 60": "/root/data/harian/ifs/LI/60.png",
  "IFS LI 63": "/root/data/harian/ifs/LI/63.png",
  "IFS LI 66": "/root/data/harian/ifs/LI/66.png",
  "IFS LI 69": "/root/data/harian/ifs/LI/69.png",
  "IFS LI 72": "/root/data/harian/ifs/LI/72.png",
  "IFS LI 75": "/root/data/harian/ifs/LI/75.png",
  "IFS LI 78": "/root/data/harian/ifs/LI/78.png",
  "IFS LI 81": "/root/data/harian/ifs/LI/81.png",
  "IFS LI 84": "/root/data/harian/ifs/LI/84.png",
  "IFS LI 87": "/root/data/harian/ifs/LI/87.png",
  "IFS LI 90": "/root/data/harian/ifs/LI/90.png",
  "IFS LI 93": "/root/data/harian/ifs/LI/93.png",
  "IFS LI 96": "/root/data/harian/ifs/LI/96.png",
  "IFS LI 99": "/root/data/harian/ifs/LI/99.png",
  "IFS LI 102": "/root/data/harian/ifs/LI/102.png",
  "IFS LI 105": "/root/data/harian/ifs/LI/105.png",
  "IFS LI 108": "/root/data/harian/ifs/LI/108.png",
  "IFS LI 111": "/root/data/harian/ifs/LI/111.png",
  "IFS LI 114": "/root/data/harian/ifs/LI/114.png",
  "IFS LI 117": "/root/data/harian/ifs/LI/117.png",
  "IFS LI 120": "/root/data/harian/ifs/LI/120.png",
  "IFS LI 123": "/root/data/harian/ifs/LI/123.png",
  "IFS LI 126": "/root/data/harian/ifs/LI/126.png",
  "IFS LI 129": "/root/data/harian/ifs/LI/129.png",
  "IFS LI 132": "/root/data/harian/ifs/LI/132.png",
  "IFS LI 135": "/root/data/harian/ifs/LI/135.png",
  "IFS LI 138": "/root/data/harian/ifs/LI/138.png",
  "IFS LI 141": "/root/data/harian/ifs/LI/141.png",
  "IFS LI 144": "/root/data/harian/ifs/LI/144.png",
  "IFS LI 147": "/root/data/harian/ifs/LI/147.png",
  "IFS LI 150": "/root/data/harian/ifs/LI/150.png",
  "IFS LI 153": "/root/data/harian/ifs/LI/153.png",
  "IFS LI 156": "/root/data/harian/ifs/LI/156.png",
  "IFS LI 159": "/root/data/harian/ifs/LI/159.png",
  "IFS LI 162": "/root/data/harian/ifs/LI/162.png",
  "IFS LI 165": "/root/data/harian/ifs/LI/165.png",
  "IFS LI 168": "/root/data/harian/ifs/LI/168.png",
  "IFS LI 171": "/root/data/harian/ifs/LI/171.png",
  "IFS LI 174": "/root/data/harian/ifs/LI/174.png",
  "IFS LI 177": "/root/data/harian/ifs/LI/177.png",
  "IFS LI 180": "/root/data/harian/ifs/LI/180.png",
  "IFS LI 183": "/root/data/harian/ifs/LI/183.png",
  "IFS LI 186": "/root/data/harian/ifs/LI/186.png",
  "IFS LI 189": "/root/data/harian/ifs/LI/189.png",
  "IFS LI 192": "/root/data/harian/ifs/LI/192.png",
  "IFS LI 195": "/root/data/harian/ifs/LI/195.png",
  "IFS LI 198": "/root/data/harian/ifs/LI/198.png",
  "IFS TT 3": "/root/data/harian/ifs/TT/3.png",
  "IFS TT 6": "/root/data/harian/ifs/TT/6.png",
  "IFS TT 9": "/root/data/harian/ifs/TT/9.png",
  "IFS TT 12": "/root/data/harian/ifs/TT/12.png",
  "IFS TT 15": "/root/data/harian/ifs/TT/15.png",
  "IFS TT 18": "/root/data/harian/ifs/TT/18.png",
  "IFS TT 21": "/root/data/harian/ifs/TT/21.png",
  "IFS TT 24": "/root/data/harian/ifs/TT/24.png",
  "IFS TT 27": "/root/data/harian/ifs/TT/27.png",
  "IFS TT 30": "/root/data/harian/ifs/TT/30.png",
  "IFS TT 33": "/root/data/harian/ifs/TT/33.png",
  "IFS TT 36": "/root/data/harian/ifs/TT/36.png",
  "IFS TT 39": "/root/data/harian/ifs/TT/39.png",
  "IFS TT 42": "/root/data/harian/ifs/TT/42.png",
  "IFS TT 45": "/root/data/harian/ifs/TT/45.png",
  "IFS TT 48": "/root/data/harian/ifs/TT/48.png",
  "IFS TT 51": "/root/data/harian/ifs/TT/51.png",
  "IFS TT 54": "/root/data/harian/ifs/TT/54.png",
  "IFS TT 57": "/root/data/harian/ifs/TT/57.png",
  "IFS TT 60": "/root/data/harian/ifs/TT/60.png",
  "IFS TT 63": "/root/data/harian/ifs/TT/63.png",
  "IFS TT 66": "/root/data/harian/ifs/TT/66.png",
  "IFS TT 69": "/root/data/harian/ifs/TT/69.png",
  "IFS TT 72": "/root/data/harian/ifs/TT/72.png",
  "IFS TT 75": "/root/data/harian/ifs/TT/75.png",
  "IFS TT 78": "/root/data/harian/ifs/TT/78.png",
  "IFS TT 81": "/root/data/harian/ifs/TT/81.png",
  "IFS TT 84": "/root/data/harian/ifs/TT/84.png",
  "IFS TT 87": "/root/data/harian/ifs/TT/87.png",
  "IFS TT 90": "/root/data/harian/ifs/TT/90.png",
  "IFS TT 93": "/root/data/harian/ifs/TT/93.png",
  "IFS TT 96": "/root/data/harian/ifs/TT/96.png",
  "IFS TT 99": "/root/data/harian/ifs/TT/99.png",
  "IFS TT 102": "/root/data/harian/ifs/TT/102.png",
  "IFS TT 105": "/root/data/harian/ifs/TT/105.png",
  "IFS TT 108": "/root/data/harian/ifs/TT/108.png",
  "IFS TT 111": "/root/data/harian/ifs/TT/111.png",
  "IFS TT 114": "/root/data/harian/ifs/TT/114.png",
  "IFS TT 117": "/root/data/harian/ifs/TT/117.png",
  "IFS TT 120": "/root/data/harian/ifs/TT/120.png",
  "IFS TT 123": "/root/data/harian/ifs/TT/123.png",
  "IFS TT 126": "/root/data/harian/ifs/TT/126.png",
  "IFS TT 129": "/root/data/harian/ifs/TT/129.png",
  "IFS TT 132": "/root/data/harian/ifs/TT/132.png",
  "IFS TT 135": "/root/data/harian/ifs/TT/135.png",
  "IFS TT 138": "/root/data/harian/ifs/TT/138.png",
  "IFS TT 141": "/root/data/harian/ifs/TT/141.png",
  "IFS TT 144": "/root/data/harian/ifs/TT/144.png",
  "IFS TT 147": "/root/data/harian/ifs/TT/147.png",
  "IFS TT 150": "/root/data/harian/ifs/TT/150.png",
  "IFS TT 153": "/root/data/harian/ifs/TT/153.png",
  "IFS TT 156": "/root/data/harian/ifs/TT/156.png",
  "IFS TT 159": "/root/data/harian/ifs/TT/159.png",
  "IFS TT 162": "/root/data/harian/ifs/TT/162.png",
  "IFS TT 165": "/root/data/harian/ifs/TT/165.png",
  "IFS TT 168": "/root/data/harian/ifs/TT/168.png",
  "IFS TT 171": "/root/data/harian/ifs/TT/171.png",
  "IFS TT 174": "/root/data/harian/ifs/TT/174.png",
  "IFS TT 177": "/root/data/harian/ifs/TT/177.png",
  "IFS TT 180": "/root/data/harian/ifs/TT/180.png",
  "IFS TT 183": "/root/data/harian/ifs/TT/183.png",
  "IFS TT 186": "/root/data/harian/ifs/TT/186.png",
  "IFS TT 189": "/root/data/harian/ifs/TT/189.png",
  "IFS TT 192": "/root/data/harian/ifs/TT/192.png",
  "IFS TT 195": "/root/data/harian/ifs/TT/195.png",
  "IFS TT 198": "/root/data/harian/ifs/TT/198.png",
  "KMA Rain 6": "/root/data/harian/kma/6.png",
  "KMA Rain 12": "/root/data/harian/kma/12.png",
  "KMA Rain 18": "/root/data/harian/kma/18.png",
  "KMA Rain 24": "/root/data/harian/kma/24.png",
  "KMA Rain 30": "/root/data/harian/kma/30.png",
  "KMA Rain 36": "/root/data/harian/kma/36.png",
  "KMA Rain 42": "/root/data/harian/kma/42.png",
  "KMA Rain 48": "/root/data/harian/kma/48.png",
  "KMA Rain 54": "/root/data/harian/kma/54.png",
  "Satelit EH": "/root/data/sepuluh/current/sat_EH.png",
  "Satelit RP": "/root/data/sepuluh/current/sat_RP.png",
  "Radar": "/root/data/sepuluh/current/citra_radar.png",
  "HotSpot Barat": "/root/data/harian/hotspot/barat.png",
  "HotSpot Timur": "/root/data/harian/hotspot/timur.png",
}

def handle(msg):
    content_type, chat_type, chat_id = telepot.glance(msg)
    print(content_type, chat_type, chat_id)

    if content_type == 'text':
        if msg["text"] == "Menu Utama":
            markup = ReplyKeyboardMarkup(keyboard=[
                     ['Satelit'],
                     ['Radar'],
                     ['Model'],
                     ['HotSpot']
                 ])
            bot.sendMessage(chat_id, 'Misi kaakk!! mau cari apa kak ??', reply_markup=markup)

        elif msg["text"] == "Satelit":
            markup = ReplyKeyboardMarkup(keyboard=[
                     ['Satelit EH'],
                     ['Satelit RP'],
                     ['Menu Utama'],
                 ])
            bot.sendMessage(chat_id, 'Misi kaakk!! mau data satelit apa kak ??', reply_markup=markup)

        elif msg["text"] == "Model":
            markup = ReplyKeyboardMarkup(keyboard=[
                     ['WRF', 'IFS'],
                     ['KMA', 'BoM'],
                     ['Menu Utama'],
                 ])
            bot.sendMessage(chat_id, 'Misi kaakk!! mau output model apa kak ??', reply_markup=markup)

        elif msg["text"] == "KMA":
            markup = ReplyKeyboardMarkup(keyboard=[
                     ['KMA Rain 6', 'KMA Rain 12', 'KMA Rain 18'],
                     ['KMA Rain 24', 'KMA Rain 30', 'KMA Rain 36'],
                     ['KMA Rain 42', 'KMA Rain 48', 'KMA Rain 54'],
                     ['Menu Utama'],
                 ])
            bot.sendMessage(chat_id, 'MMisi kaakk!! mau output jam berapa ??', reply_markup=markup)

        elif msg["text"] == "WRF":
            markup = ReplyKeyboardMarkup(keyboard=[
                     ['WRF Rain 6', 'WRF Rain 12', 'WRF Rain 18'],
                     ['WRF Rain 24', 'WRF Rain 30', 'WRF Rain 36'],
                     ['WRF Rain 42', 'WRF Rain 48', 'WRF Rain 54'],
                     ['WRF Rain 60', 'WRF Rain 66', 'WRF Rain 72'],
                     ['WRF Rain 78', 'WRF Rain 84', 'WRF Rain 90'],
                     ['WRF Rain 96', 'WRF Rain 102', 'WRF Rain 108'],
                     ['WRF Rain 114', 'WRF Rain 120'],
                     ['Menu Utama'],
                 ])
            bot.sendMessage(chat_id, 'Misi kaakk!! mau output jam berapa ??', reply_markup=markup)

        elif msg["text"] == "IFS":
            markup = ReplyKeyboardMarkup(keyboard=[
                     ['IFS Rain'],
                     ['IFS KI'],
                     ['IFS Sholwater Index'],
                     ['IFS Lifted Index'],
                     ['IFS TotalTotals'],
                     ['Menu Utama'],
                 ])
            bot.sendMessage(chat_id, 'SILAHKAN PILIH PRODUK', reply_markup=markup)

        elif msg["text"] == "IFS Rain":
            markup = ReplyKeyboardMarkup(keyboard=[
                     ['IFS RAIN 6', 'IFS RAIN 12', 'IFS RAIN 18'],
                     ['IFS RAIN 24', 'IFS RAIN 30', 'IFS RAIN 36'],
                     ['IFS RAIN 42', 'IFS RAIN 48', 'IFS RAIN 54'],
                     ['IFS RAIN 60', 'IFS RAIN 66', 'IFS RAIN 72'],
                     ['IFS RAIN 78', 'IFS RAIN 84', 'IFS RAIN 90'],
                     ['IFS RAIN 96', 'IFS RAIN 102', 'IFS RAIN 108'],
                     ['IFS RAIN 114', 'IFS RAIN 120', 'IFS RAIN 126'],
                     ['IFS RAIN 132', 'IFS RAIN 138', 'IFS RAIN 144'],
                     ['IFS RAIN 150', 'IFS RAIN 156', 'IFS RAIN 162'],
                     ['IFS RAIN 168', 'IFS RAIN 174', 'IFS RAIN 180'],
                     ['Menu Utama'],
                 ])
            bot.sendMessage(chat_id, 'Misi kaakk!! mau output jam berapa ??', reply_markup=markup)

        elif msg["text"] == "IFS KI":
            markup = ReplyKeyboardMarkup(keyboard=[
                     ['IFS KI 3', 'IFS KI 6', 'IFS KI 9'],
                     ['IFS KI 12', 'IFS KI 15', 'IFS KI 18'],
                     ['IFS KI 21', 'IFS KI 24', 'IFS KI 27'],
                     ['IFS KI 30', 'IFS KI 33', 'IFS KI 36'],
                     ['IFS KI 39', 'IFS KI 42', 'IFS KI 45'],
                     ['IFS KI 48', 'IFS KI 51', 'IFS KI 54'],
                     ['IFS KI 57', 'IFS KI 60', 'IFS KI 63'],
                     ['IFS KI 66', 'IFS KI 69', 'IFS KI 72'],
                     ['IFS KI 75', 'IFS KI 78', 'IFS KI 81'],
                     ['IFS KI 84', 'IFS KI 87', 'IFS KI 90'],
                     ['IFS KI 93', 'IFS KI 96', 'IFS KI 99'],
                     ['IFS KI 102', 'IFS KI 105', 'IFS KI 108'],
                     ['IFS KI 111', 'IFS KI 114', 'IFS KI 117'],
                     ['IFS KI 120', 'IFS KI 123', 'IFS KI 126'],
                     ['IFS KI 129', 'IFS KI 132', 'IFS KI 135'],
                     ['IFS KI 138', 'IFS KI 141', 'IFS KI 144'],
                     ['IFS KI 147', 'IFS KI 150', 'IFS KI 153'],
                     ['IFS KI 156', 'IFS KI 159', 'IFS KI 162'],
                     ['IFS KI 165', 'IFS KI 169', 'IFS KI 171'],
                     ['IFS KI 174', 'IFS KI 177', 'IFS KI 180'],
                     ['IFS KI 183', 'IFS KI 186', 'IFS KI 189'],
                     ['IFS KI 192', 'IFS KI 195', 'IFS KI 198'],
                     ['Menu Utama'],
                 ])
            bot.sendMessage(chat_id, 'Misi kaakk!! mau output jam berapa ??', reply_markup=markup)

        elif msg["text"] == "IFS Sholwater Index":
            markup = ReplyKeyboardMarkup(keyboard=[
                     ['IFS SI 3', 'IFS SI 6', 'IFS SI 9'],
                     ['IFS SI 12', 'IFS SI 15', 'IFS SI 18'],
                     ['IFS SI 21', 'IFS SI 24', 'IFS SI 27'],
                     ['IFS SI 30', 'IFS SI 33', 'IFS SI 36'],
                     ['IFS SI 39', 'IFS SI 42', 'IFS SI 45'],
                     ['IFS SI 48', 'IFS SI 51', 'IFS SI 54'],
                     ['IFS SI 57', 'IFS SI 60', 'IFS SI 63'],
                     ['IFS SI 66', 'IFS SI 69', 'IFS SI 72'],
                     ['IFS SI 75', 'IFS SI 78', 'IFS SI 81'],
                     ['IFS SI 84', 'IFS SI 87', 'IFS SI 90'],
                     ['IFS SI 93', 'IFS SI 96', 'IFS SI 99'],
                     ['IFS SI 102', 'IFS SI 105', 'IFS SI 108'],
                     ['IFS SI 111', 'IFS SI 114', 'IFS SI 117'],
                     ['IFS SI 120', 'IFS SI 123', 'IFS SI 126'],
                     ['IFS SI 129', 'IFS SI 132', 'IFS SI 135'],
                     ['IFS SI 138', 'IFS SI 141', 'IFS SI 144'],
                     ['IFS SI 147', 'IFS SI 150', 'IFS SI 153'],
                     ['IFS SI 156', 'IFS SI 159', 'IFS SI 162'],
                     ['IFS SI 165', 'IFS SI 169', 'IFS SI 171'],
                     ['IFS SI 174', 'IFS SI 177', 'IFS SI 180'],
                     ['IFS SI 183', 'IFS SI 186', 'IFS SI 189'],
                     ['IFS SI 192', 'IFS SI 195', 'IFS SI 198'],
                     ['Menu Utama'],
                 ])
            bot.sendMessage(chat_id, 'Misi kaakk!! mau output jam berapa ??', reply_markup=markup)

        elif msg["text"] == "IFS Lifted Index":
            markup = ReplyKeyboardMarkup(keyboard=[
                     ['IFS LI 3', 'IFS LI 6', 'IFS LI 9'],
                     ['IFS LI 12', 'IFS LI 15', 'IFS LI 18'],
                     ['IFS LI 21', 'IFS LI 24', 'IFS LI 27'],
                     ['IFS LI 30', 'IFS LI 33', 'IFS LI 36'],
                     ['IFS LI 39', 'IFS LI 42', 'IFS LI 45'],
                     ['IFS LI 48', 'IFS LI 51', 'IFS LI 54'],
                     ['IFS LI 57', 'IFS LI 60', 'IFS LI 63'],
                     ['IFS LI 66', 'IFS LI 69', 'IFS LI 72'],
                     ['IFS LI 75', 'IFS LI 78', 'IFS LI 81'],
                     ['IFS LI 84', 'IFS LI 87', 'IFS LI 90'],
                     ['IFS LI 93', 'IFS LI 96', 'IFS LI 99'],
                     ['IFS LI 102', 'IFS LI 105', 'IFS LI 108'],
                     ['IFS LI 111', 'IFS LI 114', 'IFS LI 117'],
                     ['IFS LI 120', 'IFS LI 123', 'IFS LI 126'],
                     ['IFS LI 129', 'IFS LI 132', 'IFS LI 135'],
                     ['IFS LI 138', 'IFS LI 141', 'IFS LI 144'],
                     ['IFS LI 147', 'IFS LI 150', 'IFS LI 153'],
                     ['IFS LI 156', 'IFS LI 159', 'IFS LI 162'],
                     ['IFS LI 165', 'IFS LI 169', 'IFS LI 171'],
                     ['IFS LI 174', 'IFS LI 177', 'IFS LI 180'],
                     ['IFS LI 183', 'IFS LI 186', 'IFS LI 189'],
                     ['IFS LI 192', 'IFS LI 195', 'IFS LI 198'],
                     ['Menu Utama'],
                 ])
            bot.sendMessage(chat_id, 'Misi kaakk!! mau output jam berapa ??', reply_markup=markup)

        elif msg["text"] == "IFS TotalTotals":
            markup = ReplyKeyboardMarkup(keyboard=[
                     ['IFS TT 3', 'IFS TT 6', 'IFS TT 9'],
                     ['IFS TT 12', 'IFS TT 15', 'IFS TT 18'],
                     ['IFS TT 21', 'IFS TT 24', 'IFS TT 27'],
                     ['IFS TT 30', 'IFS TT 33', 'IFS TT 36'],
                     ['IFS TT 39', 'IFS TT 42', 'IFS TT 45'],
                     ['IFS TT 48', 'IFS TT 51', 'IFS TT 54'],
                     ['IFS TT 57', 'IFS TT 60', 'IFS TT 63'],
                     ['IFS TT 66', 'IFS TT 69', 'IFS TT 72'],
                     ['IFS TT 75', 'IFS TT 78', 'IFS TT 81'],
                     ['IFS TT 84', 'IFS TT 87', 'IFS TT 90'],
                     ['IFS TT 93', 'IFS TT 96', 'IFS TT 99'],
                     ['IFS TT 102', 'IFS TT 105', 'IFS TT 108'],
                     ['IFS TT 111', 'IFS TT 114', 'IFS TT 117'],
                     ['IFS TT 120', 'IFS TT 123', 'IFS TT 126'],
                     ['IFS TT 129', 'IFS TT 132', 'IFS TT 135'],
                     ['IFS TT 138', 'IFS TT 141', 'IFS TT 144'],
                     ['IFS TT 147', 'IFS TT 150', 'IFS TT 153'],
                     ['IFS TT 156', 'IFS TT 159', 'IFS TT 162'],
                     ['IFS TT 165', 'IFS TT 169', 'IFS TT 171'],
                     ['IFS TT 174', 'IFS TT 177', 'IFS TT 180'],
                     ['IFS TT 183', 'IFS TT 186', 'IFS TT 189'],
                     ['IFS TT 192', 'IFS TT 195', 'IFS TT 198'],
                     ['Menu Utama'],
                 ])
            bot.sendMessage(chat_id, 'Misi kaakk!! mau output jam berapa ??', reply_markup=markup)

        elif msg["text"] == "BoM":
            markup = ReplyKeyboardMarkup(keyboard=[
                     ['BoM RAIN 6', 'BoM RAIN 12', 'BoM RAIN 18'],
                     ['BoM RAIN 24', 'BoM RAIN 30', 'BoM RAIN 36'],
                     ['BoM RAIN 42', 'BoM RAIN 48', 'BoM RAIN 54'],
                     ['BoM RAIN 60', 'BoM RAIN 66', 'BoM RAIN 72'],
                     ['BoM RAIN 78', 'BoM RAIN 84', 'BoM RAIN 90'],
                     ['BoM RAIN 96', 'BoM RAIN 102', 'BoM RAIN 108'],
                     ['BoM RAIN 114', 'BoM RAIN 120', 'BoM RAIN 126'],
                     ['BoM RAIN 132', 'BoM RAIN 138', 'BoM RAIN 144'],
                     ['BoM RAIN 150', 'BoM RAIN 156', 'BoM RAIN 162'],
                     ['Menu Utama'],
                 ])
            bot.sendMessage(chat_id, 'Misi kaakk!! mau output jam berapa ??', reply_markup=markup)

        elif msg["text"] in call_data:
            greetings = bot.sendMessage(chat_id, "Data {} Masih di Upload Bosss, tunggu yak".format(msg["text"]))
            msg_idf = telepot.message_identifier(greetings)
            bot.sendDocument(chat_id, open(call_data[msg['text']], 'rb'))
            bot.deleteMessage(msg_idf)

        elif msg["text"] == "HotSpot":
            markup = ReplyKeyboardMarkup(keyboard=[
                     ['HotSpot Barat'],
                     ['HotSpot Timur'],
                     ['Menu Utama'],
                 ])
            bot.sendMessage(chat_id, 'Misi kaakk!! mau data HotSpot bagian Indonesia mana kak ??', reply_markup=markup)

        else :
            markup = ReplyKeyboardMarkup(keyboard=[
                     ['Satelit'],
                     ['Radar'],
                     ['Model'],
                 ])
            bot.sendMessage(chat_id, 'Misi kaakk!! mau cari apa kak ??', reply_markup=markup)

        


MessageLoop(bot, {'chat': handle,
                        }).run_as_thread()

print ('Listening ...')

# Keep the program running.
while 1:
    time.sleep(10)
